# utils/pdf_generator.py
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib import colors
from pathlib import Path
from datetime import datetime

PDF_DIR = Path("generated_pdfs")
PDF_DIR.mkdir(exist_ok=True)

def generate_portfolio_pdf(data: dict) -> Path:
    filename = f"portfolio_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
    file_path = PDF_DIR / filename

    doc = SimpleDocTemplate(
        str(file_path),
        pagesize=A4,
        rightMargin=36,
        leftMargin=36,
        topMargin=36,
        bottomMargin=36,
    )

    styles = getSampleStyleSheet()
    elements = []

    # -------- STYLES --------
    title_style = ParagraphStyle(
        "Title",
        fontSize=18,
        alignment=TA_CENTER,
        spaceAfter=20,
        textColor=colors.darkblue,
        bold=True,
    )

    section_style = ParagraphStyle(
        "Section",
        fontSize=13,
        spaceBefore=14,
        spaceAfter=8,
        textColor=colors.HexColor("#1f4fd8"),
        bold=True,
    )

    body_style = ParagraphStyle(
        "Body",
        fontSize=10,
        spaceAfter=6,
        leading=14,
    )

    # -------- TITLE --------
    elements.append(Paragraph("Pharma Portfolio Intelligence Report", title_style))
    elements.append(Paragraph(
        f"<b>Query:</b> {data.get('query','-')}", body_style
    ))
    elements.append(Spacer(1, 12))

    # -------- EXECUTIVE SUMMARY --------
    elements.append(Paragraph("Executive Summary", section_style))
    elements.append(Paragraph(
        data.get("summary_text", "No summary available."),
        body_style
    ))

    # -------- MARKET SECTION --------
    market = data.get("market_data", {})
    if market:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Market Insights", section_style))
        elements.append(Paragraph(
            f"""
            <b>Therapy Area:</b> {market.get('therapy_area','N/A')}<br/>
            <b>Market Size:</b> ₹{market.get('market_size',0)/1e6:.1f} Million<br/>
            <b>CAGR:</b> {market.get('cagr','N/A')}%
            """,
            body_style
        ))

    # -------- TRADE SECTION --------
    trade = data.get("trade_data", {})
    if trade:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Trade & Supply Insights", section_style))
        elements.append(Paragraph(
            f"""
            <b>API:</b> {trade.get('api_name','N/A')}<br/>
            <b>Export Volume:</b> {trade.get('export_volume_kg','N/A')} kg<br/>
            <b>Import Dependency:</b> {trade.get('import_dependency','N/A')}
            """,
            body_style
        ))

    # -------- PATENT SECTION --------
    patent = data.get("patent_data", {})
    if patent:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Patent Landscape", section_style))
        elements.append(Paragraph(
            f"""
            <b>Patent Number:</b> {patent.get('patent_number','N/A')}<br/>
            <b>Expiry Date:</b> {patent.get('expiry_date','N/A')}<br/>
            <b>FTO Status:</b> {patent.get('fto_flag','N/A')}
            """,
            body_style
        ))

    # -------- CLINICAL TRIALS --------
    trials = data.get("trials", [])
    if trials:
        elements.append(Spacer(1, 10))
        elements.append(Paragraph("Clinical Trials Snapshot", section_style))

        table_data = [["Phase", "Status", "Country"]]
        for t in trials[:5]:
            table_data.append([
                str(t.get("phase","-")),
                t.get("status","-"),
                t.get("country","-"),
            ])

        table = Table(table_data, colWidths=[80, 200, 120])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("GRID", (0,0), (-1,-1), 0.5, colors.grey),
            ("FONT", (0,0), (-1,0), "Helvetica-Bold"),
            ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ]))

        elements.append(table)

    # -------- FOOTER --------
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        "<i>Generated by Agentic AI Pharma Intelligence Platform</i>",
        ParagraphStyle("Footer", fontSize=8, alignment=TA_CENTER, textColor=colors.grey)
    ))

    doc.build(elements)
    return file_path